---
title: "Untitled"
author: "Gabe Runte"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(gganimate)
library(gifski)
library(viridis)
library(viridisLite)
library(plotly)
library(ggpubr)
library(patchwork)
library(rayshader)
library(RSelenium)


b.color = "#85A389"
n.color = "#A2CDB0"
f.color = "#F1C27B"

prim.color = "#3b78a3"
alt.color = "#bd4665"
```

```{r, echo = FALSE}
st.pts = seq(1,125, length.out = 15)

for(j in 1:length(st.pts)){

tset = seq(from = 0, to = 50, by = 0.01)
a <- 0.25
p1 <- .5
mB1 <- .15
mN1 <- mB1
epsilon <- 0.15
mF1 <- 0.1
u1 <- .25
N0 <- 100

#holding vectors and initial conditions
b1.set = rep(NaN, length(tset)); b1.set[1] <- st.pts[j]
n1.set = rep(NaN, length(tset)); n1.set[1] <- b1.set[1]*0.5
f1.set = rep(NaN, length(tset)); f1.set[1] <- b1.set[1]*0.15
e.set = rep(NaN, length(tset));  e.set[1]  <- 100 - n1.set[1]

for(i in 2:length(tset)){
  dt <- tset[i]-tset[i-1]
  B1 <- b1.set[i-1];  N1 <- n1.set[i-1]; F1 <- f1.set[i-1]; E <- e.set[i-1]

  dB1 <- (p1*N1 - (a+mB1)*B1)*dt
  dN1 <- (E*(u1*F1) - mN1*N1)*dt
  dF1 <- ((a*B1)*epsilon - mF1*F1)*dt

b1.set[i] <- B1 + dB1;n1.set[i] <- N1 + dN1;f1.set[i] <- F1 + dF1;e.set[i] <- E - (dN1)}

if(j == 1)
{total.1t1f = tibble(time = tset) %>% 
  mutate(b1 = b1.set)%>% 
  mutate(n1 = n1.set)%>% 
  mutate(f1 = f1.set)%>% 
  mutate(e = e.set) %>% 
  mutate(st.pt = b1.set[1])}
if(j>1)
{loop.df = tibble(time = tset) %>% 
  mutate(b1 = b1.set)%>% 
  mutate(n1 = n1.set)%>% 
  mutate(f1 = f1.set)%>% 
  mutate(e = e.set) %>% 
  mutate(st.pt = b1.set[1])
  total.1t1f = total.1t1f %>% 
    bind_rows(loop.df)}
}
long.1t1f = total.1t1f %>% 
  pivot_longer(cols = b1:f1, names_to = "pool", values_to = 'size') %>% 
  mutate(plot.group = paste0(pool, st.pt)) %>% 
  group_by(plot.group) %>% 
 slice(which(row_number() %% 10 == 1)) 

ggplot(long.1t1f, aes(x = time, y = size, color = pool, group = plot.group))+geom_line(aes(alpha = st.pt), size = 2)+
  scale_color_manual(name = "", breaks = c("b1", "n1", "f1"), labels = c("Host biomass", "Host nitrogen", "Fungal biomass"), values = c(b.color, n.color, f.color))+
  labs(x = "Time (yrs)", y = "Pool sizes", title = "A One-tree-one-fungus System from different initial conditions")+theme_minimal()+ guides(alpha =  FALSE)

```





```{r injury stress test, eval = F, echo = F}
steps = 5
part.increments = seq(0.5, 1, length.out = steps)
roi.increments = seq(0, 1, length.out = steps)


samset = tibble(
  partner.pref = part.increments, 
  roi.host = roi.increments,
  roi.symb = roi.increments
)

samsetlong = samset %>% 
  expand.grid()
p.pref = as.vector(samsetlong$partner.pref)
host_roi = as.vector(samsetlong$roi.host)
symb_roi = as.vector(samsetlong$roi.symb)

b1.recovery = rep(NaN, length(p.pref))

for(j in 1:length(p.pref)){

primary.weight = p.pref[j] # how much preference each member of the network has for it's primary partner (e.g. Fungus 2's preference for Host 2)
#parameter values
tset = seq(from = 0, to = 500, by = 0.1) # a timeseries to iterate over
a <- 0.25 # host allocation to symbiont
p1 <- 0.5#(sin((2*pi/1000)*tset) + 1) / 2 # host 1 photosynthetic rate
p2 <- 0.5#1-(sin((2*pi/1000)*tset) + 1) / 2 # host 2 photosynthetic rate
mB1 <- .15 # host 1 mortality
mB2 <- .15 # host 2 mortality
mN1 <- mB1 # host 1 nitrogen loss rate
mN2 <- mB2 # host 2 nitrogen loss rate
r11 <- primary.weight # preference of host 1 toward fungus 1
r12 <- 1-r11 # preference of host 1 toward fungus 2
r22 <- primary.weight # preference of host 2 toward fungus 2
r21 <- 1-r22 # preference of host 2 toward fungus 1
epsilon <- 0.15 # fungal conversion efficiency
mF1 <- 0.1 # fungus 1 mortality rate
mF2 <- mF1 # fungus 2 mortality rate
u1 <- .25 # fungus 1 uptake rate
u2 <- .25 # fungus 2 uptake rate
s11 <- primary.weight # preference of fungus 1 toward host 1
s12 <- 1-s11 # preference of fungus 1 toward host 2
s22 <- primary.weight # preference of fungus 2 toward host 2
s21 <- 1-s22 # preference of fungus 2 toward host 1
N0 <- 100 # total system nitrogen
l.h = host_roi[j] # percent of tree resources lost from ROI allocation
l.s = symb_roi[j] # percent of fungal resources lost from ROI allocation


#holding vectors and initial conditions
b1.set = rep(NaN, length(tset)); b1.set[1] <- 50
b2.set = rep(NaN, length(tset)); b2.set[1] <- 50
n1.set = rep(NaN, length(tset)); n1.set[1] <- b1.set[1]*0.5
n2.set = rep(NaN, length(tset)); n2.set[1] <- b2.set[1]*0.5
f1.set = rep(NaN, length(tset)); f1.set[1] <- b1.set[1]*0.15
f2.set = rep(NaN, length(tset)); f2.set[1] <- b1.set[1]*0.15
e.set = rep(NaN, length(tset));  e.set[1]  <- 100 - n1.set[1]-n2.set[1]

#historical sharing percentages based on relative size of each 
c1f1.set = rep(NaN, length(tset)); c1f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c1f2.set = rep(NaN, length(tset)); c1f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
c2f1.set = rep(NaN, length(tset)); c2f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c2f2.set = rep(NaN, length(tset)); c2f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
f1n1.set = rep(NaN, length(tset)); f1n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f1n2.set = rep(NaN, length(tset)); f1n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])
f2n1.set = rep(NaN, length(tset)); f2n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f2n2.set = rep(NaN, length(tset)); f2n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])


for(i in 2:length(tset)){
  dt <- tset[i]-tset[i-1]
  B1 <- b1.set[i-1];  N1 <- n1.set[i-1]; F1 <- f1.set[i-1]
  B2 <- b2.set[i-1];  N2 <- n2.set[i-1];F2 <- f2.set[i-1]; E <- e.set[i-1]
  c1tof1 <- c1f1.set[i-1]; c1tof2 <- c1f2.set[i-1]; c2tof1 <- c2f1.set[i-1]; c2tof2 <- c2f2.set[i-1]
  f1ton1 <- f1n1.set[i-1]; f1ton2 <- f1n2.set[i-1]; f2ton1 <- f2n1.set[i-1]; f2ton2 <- f2n2.set[i-1]

  dB1 <- (p1 * N1 - (a + mB1)*B1)*dt
  dN1 <- (E*(u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))-mN1*N1)*dt
  dB2 <- (p2 * N2 - (a + mB2)*B2)*dt
  dN2 <- (E*(u1*F1*f1ton2*(1-l.s)+u1*F1*s12*l.s+u2*F2*f2ton2*(1-l.s)+u2*F2*s22*l.s)-mN2*N2)*dt
  dF1 <- ((a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)*epsilon+(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)*epsilon-mF1*F1)*dt
  dF2 <- ((a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)*epsilon+(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)*epsilon-mF2*F2)*dt

c1tof1.new <- r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c1tof2.new <- r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c2tof1.new <- r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
c2tof2.new <- r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
f1ton1.new <- s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f1ton2.new <- s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f2ton1.new <- s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))
f2ton2.new <- s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))

if(i == round(0.5*length(tset), 0))
{dB1 <- -0.25*B1}

b1.set[i] <- B1 + dB1;n1.set[i] <- N1 + dN1;f1.set[i] <- F1 + dF1
b2.set[i] <- B2 + dB2;n2.set[i] <- N2 + dN2;f2.set[i] <- F2 + dF2;e.set[i] <- E - (dN1 + dN2)
  
c1f1.set[i]<- c1tof1.new;c1f2.set[i]<- c1tof2.new;c2f1.set[i]<- c2tof1.new;c2f2.set[i]<- c2tof2.new
f1n1.set[i]<- f1ton1.new;f1n2.set[i]<- f1ton2.new;f2n1.set[i]<- f2ton1.new;f2n2.set[i]<- f2ton2.new
}
b1.recovery[j] = max(tset)*(which(b1.set[round(0.5*length(tset),0):length(b1.set)] > 0.99*b1.set[round(0.5*length(tset),0)-1])[1] )/length(tset)

}
injury_recovery = samsetlong  %>% 
  rename(partner.preference = partner.pref) %>% 
  rename(ROI.host = roi.host) %>% 
  mutate(ROI.host = 1-ROI.host) %>% 
  rename(ROI.symb = roi.symb) %>% 
  mutate(ROI.symb = 1-ROI.symb)%>% 
  mutate(time_to_recovery = b1.recovery)

ggplot(injury_recovery, aes(x = partner.preference, y = ROI.host, fill = time_to_recovery))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Time to Recovery")+facet_grid(cols = vars(ROI.symb))+ theme(aspect.ratio=15/15)
```


```{r}
primary.weight = .55 # how much preference each member of the network has for it's primary partner (e.g. Fungus 2's preference for Host 2)
#parameter values
tset = seq(from = 0, to = 500, by = 0.1) # a timeseries to iterate over
a <- 0.25 # host allocation to symbiont
p1 <- 0.5#(sin((2*pi/1000)*tset) + 1) / 2 # host 1 photosynthetic rate
p2 <- 0.5#1-(sin((2*pi/1000)*tset) + 1) / 2 # host 2 photosynthetic rate
mB1 <- .15 # host 1 mortality
mB2 <- .15 # host 2 mortality
mN1 <- mB1 # host 1 nitrogen loss rate
mN2 <- mB2 # host 2 nitrogen loss rate
r11 <- primary.weight # preference of host 1 toward fungus 1
r12 <- 1-r11 # preference of host 1 toward fungus 2
r22 <- primary.weight # preference of host 2 toward fungus 2
r21 <- 1-r22 # preference of host 2 toward fungus 1
epsilon <- 0.15 # fungal conversion efficiency
mF1 <- 0.1 # fungus 1 mortality rate
mF2 <- mF1 # fungus 2 mortality rate
u1 <- .25 # fungus 1 uptake rate
u2 <- .25 # fungus 2 uptake rate
s11 <- primary.weight # preference of fungus 1 toward host 1
s12 <- 1-s11 # preference of fungus 1 toward host 2
s22 <- primary.weight # preference of fungus 2 toward host 2
s21 <- 1-s22 # preference of fungus 2 toward host 1
N0 <- 100 # total system nitrogen
l.h = .25 # percent of tree resources lost from ROI allocation
l.s = .5 # percent of fungal resources lost from ROI allocation


#holding vectors and initial conditions
b1.set = rep(NaN, length(tset)); b1.set[1] <- 50
b2.set = rep(NaN, length(tset)); b2.set[1] <- 50
n1.set = rep(NaN, length(tset)); n1.set[1] <- b1.set[1]*0.5
n2.set = rep(NaN, length(tset)); n2.set[1] <- b2.set[1]*0.5
f1.set = rep(NaN, length(tset)); f1.set[1] <- b1.set[1]*0.15
f2.set = rep(NaN, length(tset)); f2.set[1] <- b1.set[1]*0.15
e.set = rep(NaN, length(tset));  e.set[1]  <- 100 - n1.set[1]-n2.set[1]

#historical sharing percentages based on relative size of each 
c1f1.set = rep(NaN, length(tset)); c1f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c1f2.set = rep(NaN, length(tset)); c1f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
c2f1.set = rep(NaN, length(tset)); c2f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c2f2.set = rep(NaN, length(tset)); c2f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
f1n1.set = rep(NaN, length(tset)); f1n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f1n2.set = rep(NaN, length(tset)); f1n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])
f2n1.set = rep(NaN, length(tset)); f2n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f2n2.set = rep(NaN, length(tset)); f2n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])


for(i in 2:length(tset)){
  dt <- tset[i]-tset[i-1]
  B1 <- b1.set[i-1];  N1 <- n1.set[i-1]; F1 <- f1.set[i-1]
  B2 <- b2.set[i-1];  N2 <- n2.set[i-1];F2 <- f2.set[i-1]; E <- e.set[i-1]
  c1tof1 <- c1f1.set[i-1]; c1tof2 <- c1f2.set[i-1]; c2tof1 <- c2f1.set[i-1]; c2tof2 <- c2f2.set[i-1]
  f1ton1 <- f1n1.set[i-1]; f1ton2 <- f1n2.set[i-1]; f2ton1 <- f2n1.set[i-1]; f2ton2 <- f2n2.set[i-1]

  dB1 <- (p1 * N1 - (a + mB1)*B1)*dt
  dN1 <- (E*(u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))-mN1*N1)*dt
  dB2 <- (p2 * N2 - (a + mB2)*B2)*dt
  dN2 <- (E*(u1*F1*f1ton2*(1-l.s)+u1*F1*s12*l.s+u2*F2*f2ton2*(1-l.s)+u2*F2*s22*l.s)-mN2*N2)*dt
  dF1 <- ((a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)*epsilon+(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)*epsilon-mF1*F1)*dt
  dF2 <- ((a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)*epsilon+(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)*epsilon-mF2*F2)*dt

c1tof1.new <- r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c1tof2.new <- r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c2tof1.new <- r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
c2tof2.new <- r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
f1ton1.new <- s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f1ton2.new <- s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f2ton1.new <- s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))
f2ton2.new <- s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))

if(i == round(0.55*length(tset), 0))
{p1 = 0.75*p2}
if(i == round(0.6*length(tset), 0))
{p1 = p2}

b1.set[i] <- B1 + dB1;n1.set[i] <- N1 + dN1;f1.set[i] <- F1 + dF1
b2.set[i] <- B2 + dB2;n2.set[i] <- N2 + dN2;f2.set[i] <- F2 + dF2;e.set[i] <- E - (dN1 + dN2)
  
c1f1.set[i]<- c1tof1.new;c1f2.set[i]<- c1tof2.new;c2f1.set[i]<- c2tof1.new;c2f2.set[i]<- c2tof2.new
f1n1.set[i]<- f1ton1.new;f1n2.set[i]<- f1ton2.new;f2n1.set[i]<- f2ton1.new;f2n2.set[i]<- f2ton2.new
}

sim.2t2f.temp = tibble(time = tset) %>% 
  mutate(b1 = b1.set)%>% 
  mutate(b2 = b2.set)%>% 
  mutate(n1 = n1.set)%>% 
  mutate(n2 = n2.set) %>% 
  mutate(f1 = f1.set)%>% 
  mutate(f2 = f2.set) %>%  
  mutate(e = e.set) %>%
  mutate(c1f1 = c1f1.set)%>% 
  mutate(c1f2 = c1f2.set)%>% 
  mutate(c2f1 = c2f1.set)%>% 
  mutate(c2f2 = c2f2.set)%>% 
  mutate(f1n1 = f1n1.set)%>% 
  mutate(f1n2 = f1n2.set)%>% 
  mutate(f2n1 = f2n1.set)%>% 
  mutate(f2n2 = f2n2.set) 

long.2t2f.temp = sim.2t2f.temp %>% 
  select(time:f2) %>% 
  pivot_longer(cols = b1:f2, names_to = "pool", values_to = 'size') %>% 
  mutate(rep = str_sub(pool, 2,2)) %>% 
  mutate(pool = str_sub(pool, 1,1)) %>%
  group_by(pool, rep) %>% 
 slice(which(row_number() %% 501 == 1)) %>% 
  mutate(rep = case_when(
    rep == "1" ~ "Host/Fungus 1",
    rep == "2" ~ "Host/Fungus 2"
  ))



  ggplot(long.2t2f.temp, aes(x = time, y = size, color = pool))+
  geom_line(aes(linetype = rep), size = 1.5)+ 
  facet_wrap(~rep)+
  labs(x = "Time", y = "Pool Size", "Different initial conditions")+
  scale_color_manual(name = "", breaks = c("b", "n", "f"), labels = c("Host biomass", "Host nitrogen", "Fungal biomass"), values = c(b.color, n.color, f.color))+
  theme_classic()+guides(linetype = "none")#+transition_reveal(time)
  
#  ggsave(here("labmeetings/explanation_stressor.png"), width = 7, height = 5)
```

```{r, eval = F}
steps = 12
part.increments = seq(0.5, 1, length.out = steps)
roi.increments = seq(0, 1, length.out = steps)


samset = tibble(
  partner.pref = part.increments, 
  roi.host = roi.increments,
  roi.symb = roi.increments
)

samsetlong = samset %>% 
  expand.grid()
p.pref = as.vector(samsetlong$partner.pref)
host_roi = as.vector(samsetlong$roi.host)
symb_roi = as.vector(samsetlong$roi.symb)

b1.resistance = rep(NaN, length(p.pref))
b1.recovery_time = rep(NaN, length(p.pref))
b1.recovery_percent = rep(NaN, length(p.pref))
f1.resistance = rep(NaN, length(p.pref))
f1.recovery_time = rep(NaN, length(p.pref))
f1.recovery_percent = rep(NaN, length(p.pref))

for(j in 1:length(p.pref)){

primary.weight = p.pref[j] # how much preference each member of the network has for it's primary partner (e.g. Fungus 2's preference for Host 2)
#parameter values
tset = seq(from = 0, to = 5000, by = 0.1) # a timeseries to iterate over
a <- 0.25 # host allocation to symbiont
p1 <- 0.5#(sin((2*pi/1000)*tset) + 1) / 2 # host 1 photosynthetic rate
p2 <- 0.5#1-(sin((2*pi/1000)*tset) + 1) / 2 # host 2 photosynthetic rate
mB1 <- .15 # host 1 mortality
mB2 <- .15 # host 2 mortality
mN1 <- mB1 # host 1 nitrogen loss rate
mN2 <- mB2 # host 2 nitrogen loss rate
r11 <- primary.weight # preference of host 1 toward fungus 1
r12 <- 1-r11 # preference of host 1 toward fungus 2
r22 <- primary.weight # preference of host 2 toward fungus 2
r21 <- 1-r22 # preference of host 2 toward fungus 1
epsilon <- 0.15 # fungal conversion efficiency
mF1 <- 0.1 # fungus 1 mortality rate
mF2 <- mF1 # fungus 2 mortality rate
u1 <- .25 # fungus 1 uptake rate
u2 <- .25 # fungus 2 uptake rate
s11 <- primary.weight # preference of fungus 1 toward host 1
s12 <- 1-s11 # preference of fungus 1 toward host 2
s22 <- primary.weight # preference of fungus 2 toward host 2
s21 <- 1-s22 # preference of fungus 2 toward host 1
N0 <- 100 # total system nitrogen
l.h = host_roi[j] # percent of tree resources lost from ROI allocation
l.s = symb_roi[j] # percent of fungal resources lost from ROI allocation


#holding vectors and initial conditions
b1.set = rep(NaN, length(tset)); b1.set[1] <- 50
b2.set = rep(NaN, length(tset)); b2.set[1] <- 50
n1.set = rep(NaN, length(tset)); n1.set[1] <- b1.set[1]*0.5
n2.set = rep(NaN, length(tset)); n2.set[1] <- b2.set[1]*0.5
f1.set = rep(NaN, length(tset)); f1.set[1] <- b1.set[1]*0.15
f2.set = rep(NaN, length(tset)); f2.set[1] <- b1.set[1]*0.15
e.set = rep(NaN, length(tset));  e.set[1]  <- 100 - n1.set[1]-n2.set[1]

#historical sharing percentages based on relative size of each 
c1f1.set = rep(NaN, length(tset)); c1f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c1f2.set = rep(NaN, length(tset)); c1f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
c2f1.set = rep(NaN, length(tset)); c2f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c2f2.set = rep(NaN, length(tset)); c2f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
f1n1.set = rep(NaN, length(tset)); f1n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f1n2.set = rep(NaN, length(tset)); f1n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])
f2n1.set = rep(NaN, length(tset)); f2n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f2n2.set = rep(NaN, length(tset)); f2n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])


for(i in 2:length(tset)){
  dt <- tset[i]-tset[i-1]
  B1 <- b1.set[i-1];  N1 <- n1.set[i-1]; F1 <- f1.set[i-1]
  B2 <- b2.set[i-1];  N2 <- n2.set[i-1];F2 <- f2.set[i-1]; E <- e.set[i-1]
  c1tof1 <- c1f1.set[i-1]; c1tof2 <- c1f2.set[i-1]; c2tof1 <- c2f1.set[i-1]; c2tof2 <- c2f2.set[i-1]
  f1ton1 <- f1n1.set[i-1]; f1ton2 <- f1n2.set[i-1]; f2ton1 <- f2n1.set[i-1]; f2ton2 <- f2n2.set[i-1]

  dB1 <- (p1 * N1 - (a + mB1)*B1)*dt
  dN1 <- (E*(u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))-mN1*N1)*dt
  dB2 <- (p2 * N2 - (a + mB2)*B2)*dt
  dN2 <- (E*(u1*F1*f1ton2*(1-l.s)+u1*F1*s12*l.s+u2*F2*f2ton2*(1-l.s)+u2*F2*s22*l.s)-mN2*N2)*dt
  dF1 <- ((a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)*epsilon+(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)*epsilon-mF1*F1)*dt
  dF2 <- ((a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)*epsilon+(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)*epsilon-mF2*F2)*dt

c1tof1.new <- r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c1tof2.new <- r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c2tof1.new <- r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
c2tof2.new <- r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
f1ton1.new <- s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f1ton2.new <- s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f2ton1.new <- s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))
f2ton2.new <- s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))

if(i == round(0.55*length(tset), 0))
{p1 = 0.75*p2}
if(i == round(0.6*length(tset), 0))
{p1 = p2}

b1.set[i] <- B1 + dB1;n1.set[i] <- N1 + dN1;f1.set[i] <- F1 + dF1
b2.set[i] <- B2 + dB2;n2.set[i] <- N2 + dN2;f2.set[i] <- F2 + dF2;e.set[i] <- E - (dN1 + dN2)
  
c1f1.set[i]<- c1tof1.new;c1f2.set[i]<- c1tof2.new;c2f1.set[i]<- c2tof1.new;c2f2.set[i]<- c2tof2.new
f1n1.set[i]<- f1ton1.new;f1n2.set[i]<- f1ton2.new;f2n1.set[i]<- f2ton1.new;f2n2.set[i]<- f2ton2.new
}

b1.resistance[j] = min(b1.set[round(0.55*length(tset),0):length(b1.set)])/b1.set[round(0.55*length(tset),0)]
b1.recovery_time[j] = max(tset)*(which(b1.set[round(0.6*length(tset),0):length(b1.set)] > 0.99*b1.set[round(0.55*length(tset),0)-1])[1] )/length(tset)
b1.recovery_percent[j] = b1.set[length(b1.set)]/b1.set[round(0.55*length(tset),0)-1]
f1.resistance[j] = min(f1.set[round(0.55*length(tset),0):length(f1.set)])/f1.set[round(0.55*length(tset),0)]
f1.recovery_time[j] = max(tset)*(which(f1.set[round(0.6*length(tset),0):length(f1.set)] > 0.99*f1.set[round(0.55*length(tset),0)-1])[1] )/length(tset)
f1.recovery_percent[j] = f1.set[length(f1.set)]/f1.set[round(0.55*length(tset),0)-1]
}
stress_response = samsetlong  %>% 
  rename(partner.preference = partner.pref) %>% 
  rename(ROI.host = roi.host) %>% 
  mutate(ROI.host = 1-ROI.host) %>% 
  rename(ROI.symb = roi.symb) %>% 
  mutate(ROI.symb = 1-ROI.symb)%>% 
  mutate(host_resistance = b1.resistance)%>% 
  mutate(host_recovery_time = b1.recovery_time)%>% 
  mutate(host_recovery_percent = b1.recovery_percent) %>% 
  mutate(host_resilience = host_recovery_percent/host_recovery_time) %>% 
  mutate(symb_resistance = f1.resistance)%>% 
  mutate(symb_recovery_time = f1.recovery_time)%>% 
  mutate(symb_recovery_percent = f1.recovery_percent) %>% 
  mutate(symb_resilience = symb_recovery_percent/symb_recovery_time) %>% 
  mutate(Fungal.ROI = ROI.symb)%>% 
  mutate(Host.ROI = ROI.host)
```


```{r, eval = F}
host_resistance.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resistance")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Host Resistance (Minimum relative size of stressed host)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

host_recoverypercent.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = host_recovery_percent))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Recovery percent")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Host Percent host recovery after stress", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

host_recoverytime.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = host_recovery_time))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Time")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = " Host Time to full recovery", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

host_resilience.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = host_resilience))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resilience")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Host Resilience (% recovery/time to recovery)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

host_resistance.plot / host_recoverypercent.plot / host_recoverytime.plot / host_resilience.plot
ggsave(here("src/piecemeal", "host_treestress_superplot.png"), width = 14, height = 10)

#----------------------------------
symb_resistance.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_resistance))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resistance")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Fungal Resistance (Minimum relative size of stressed host)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

symb_recoverypercent.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_recovery_percent))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Recovery percent")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Fungal Percent host recovery after stress", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

symb_recoverytime.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_recovery_time))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Time")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Fungal Time to full recovery", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

symb_resilience.plot = ggplot(stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_resilience))+ geom_tile()+ 
  scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resilience")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
  labs(title = "Fungal Resilience (% recovery/time to recovery)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")

symb_resistance.plot / symb_recoverypercent.plot / symb_recoverytime.plot / symb_resilience.plot
ggsave(here("src/piecemeal", "symb_treestress_superplot.png"), width = 14, height = 10)

```


```{r}
stress_scaled = stress_response %>% 
  mutate(partner.preference = 2*(partner.preference-0.5)) 

plot_ly(x=stress_scaled$partner.preference, y=stress_scaled$ROI.host, z=stress_scaled$ROI.symb, 
        type="scatter3d", mode="markers", color=stress_scaled$host_resistance) %>% 
  layout(scene = list(xaxis=list(title = "Partner Preference"), 
                                    yaxis=list(title = "Tree ROI"),
                                    zaxis=list(title = "Fungal ROI")))

df.set = stress_scaled %>% 
         filter(ROI.symb == 0)


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")

df.set = stress_scaled %>% 
         filter(ROI.symb == 1)
plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))%>% colorbar(title = "Resilience")

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))%>% colorbar(title = "Resistance")
# %>% colorbar(title = "Resilience")%>%
  # config(
  #   toImageButtonOptions = list(
  #     format = "svg",
  #     filename = "myplot",
  #     width = 700,
  #     height = 500
  #   )
  # )
```

```{r}

df.set = stress_scaled %>% 
         filter(ROI.symb == 0)


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()
ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = stress_scaled %>% 
         filter(ROI.symb == 6/11)


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()
ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = stress_scaled %>% 
         filter(ROI.symb == 1)


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()
ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")
```

```{r}

df.set = stress_scaled %>% 
         filter(ROI.host == 0)


ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = stress_scaled %>% 
         filter(ROI.host == 6/11)


ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = stress_scaled %>% 
         filter(ROI.host == 1)


ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")
```

## Fungus is stressed
```{r, eval = F}
steps = 10
part.increments = seq(0.5, 1, length.out = steps)
roi.increments = seq(0, 1, length.out = steps)


samset = tibble(
  partner.pref = part.increments, 
  roi.host = roi.increments,
  roi.symb = roi.increments
)

samsetlong = samset %>% 
  expand.grid()
p.pref = as.vector(samsetlong$partner.pref)
host_roi = as.vector(samsetlong$roi.host)
symb_roi = as.vector(samsetlong$roi.symb)

b1.resistance = rep(NaN, length(p.pref))
b1.recovery_time = rep(NaN, length(p.pref))
b1.recovery_percent = rep(NaN, length(p.pref))
f1.resistance = rep(NaN, length(p.pref))
f1.recovery_time = rep(NaN, length(p.pref))
f1.recovery_percent = rep(NaN, length(p.pref))

for(j in 1:length(p.pref)){

primary.weight = p.pref[j] # how much preference each member of the network has for it's primary partner (e.g. Fungus 2's preference for Host 2)
#parameter values
tset = seq(from = 0, to = 5000, by = 0.1) # a timeseries to iterate over
a <- 0.25 # host allocation to symbiont
p1 <- 0.5#(sin((2*pi/1000)*tset) + 1) / 2 # host 1 photosynthetic rate
p2 <- 0.5#1-(sin((2*pi/1000)*tset) + 1) / 2 # host 2 photosynthetic rate
mB1 <- .15 # host 1 mortality
mB2 <- .15 # host 2 mortality
mN1 <- mB1 # host 1 nitrogen loss rate
mN2 <- mB2 # host 2 nitrogen loss rate
r11 <- primary.weight # preference of host 1 toward fungus 1
r12 <- 1-r11 # preference of host 1 toward fungus 2
r22 <- primary.weight # preference of host 2 toward fungus 2
r21 <- 1-r22 # preference of host 2 toward fungus 1
epsilon <- 0.15 # fungal conversion efficiency
mF1 <- 0.1 # fungus 1 mortality rate
mF2 <- mF1 # fungus 2 mortality rate
u1 <- .25 # fungus 1 uptake rate
u2 <- .25 # fungus 2 uptake rate
s11 <- primary.weight # preference of fungus 1 toward host 1
s12 <- 1-s11 # preference of fungus 1 toward host 2
s22 <- primary.weight # preference of fungus 2 toward host 2
s21 <- 1-s22 # preference of fungus 2 toward host 1
N0 <- 100 # total system nitrogen
l.h = host_roi[j] # percent of tree resources lost from ROI allocation
l.s = symb_roi[j] # percent of fungal resources lost from ROI allocation


#holding vectors and initial conditions
b1.set = rep(NaN, length(tset)); b1.set[1] <- 50
b2.set = rep(NaN, length(tset)); b2.set[1] <- 50
n1.set = rep(NaN, length(tset)); n1.set[1] <- b1.set[1]*0.5
n2.set = rep(NaN, length(tset)); n2.set[1] <- b2.set[1]*0.5
f1.set = rep(NaN, length(tset)); f1.set[1] <- b1.set[1]*0.15
f2.set = rep(NaN, length(tset)); f2.set[1] <- b1.set[1]*0.15
e.set = rep(NaN, length(tset));  e.set[1]  <- 100 - n1.set[1]-n2.set[1]

#historical sharing percentages based on relative size of each 
c1f1.set = rep(NaN, length(tset)); c1f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c1f2.set = rep(NaN, length(tset)); c1f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
c2f1.set = rep(NaN, length(tset)); c2f1.set[1] <- f1.set[1]/(f1.set[1]+f2.set[1])
c2f2.set = rep(NaN, length(tset)); c2f2.set[1] <- f2.set[1]/(f1.set[1]+f2.set[1])
f1n1.set = rep(NaN, length(tset)); f1n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f1n2.set = rep(NaN, length(tset)); f1n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])
f2n1.set = rep(NaN, length(tset)); f2n1.set[1] <- b1.set[1]/(b1.set[1]+b2.set[1])
f2n2.set = rep(NaN, length(tset)); f2n2.set[1] <- b2.set[1]/(b1.set[1]+b2.set[1])


for(i in 2:length(tset)){
  dt <- tset[i]-tset[i-1]
  B1 <- b1.set[i-1];  N1 <- n1.set[i-1]; F1 <- f1.set[i-1]
  B2 <- b2.set[i-1];  N2 <- n2.set[i-1];F2 <- f2.set[i-1]; E <- e.set[i-1]
  c1tof1 <- c1f1.set[i-1]; c1tof2 <- c1f2.set[i-1]; c2tof1 <- c2f1.set[i-1]; c2tof2 <- c2f2.set[i-1]
  f1ton1 <- f1n1.set[i-1]; f1ton2 <- f1n2.set[i-1]; f2ton1 <- f2n1.set[i-1]; f2ton2 <- f2n2.set[i-1]

  dB1 <- (p1 * N1 - (a + mB1)*B1)*dt
  dN1 <- (E*(u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))-mN1*N1)*dt
  dB2 <- (p2 * N2 - (a + mB2)*B2)*dt
  dN2 <- (E*(u1*F1*f1ton2*(1-l.s)+u1*F1*s12*l.s+u2*F2*f2ton2*(1-l.s)+u2*F2*s22*l.s)-mN2*N2)*dt
  dF1 <- ((a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)*epsilon+(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)*epsilon-mF1*F1)*dt
  dF2 <- ((a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)*epsilon+(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)*epsilon-mF2*F2)*dt

c1tof1.new <- r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c1tof2.new <- r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s)/(r11*u1*(F1*f1ton1*(1-l.s)+F1*s11*l.s)+r12*u2*(F2*f2ton1*(1-l.s)+F2*s21*l.s))
c2tof1.new <- r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
c2tof2.new <- r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s)/(r21*u1*(F1*f1ton2*(1-l.s)+F1*s12*l.s)+r22*u2*(F2*f2ton2*(1-l.s)+F2*s22*l.s))
f1ton1.new <- s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f1ton2.new <- s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21)/(s11*(a*B1*c1tof1*(1-l.h)+l.h*a*B1*r11)+s12*(a*B2*c2tof1*(1-l.h)+l.h*a*B2*r21))
f2ton1.new <- s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))
f2ton2.new <- s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22)/(s21*(a*B1*c1tof2*(1-l.h)+l.h*a*B1*r12)+s22*(a*B2*c2tof2*(1-l.h)+l.h*a*B2*r22))

if(i == round(0.55*length(tset), 0))
{u1 = 0.75*u2}
if(i == round(0.6*length(tset), 0))
{u1 = u2}

b1.set[i] <- B1 + dB1;n1.set[i] <- N1 + dN1;f1.set[i] <- F1 + dF1
b2.set[i] <- B2 + dB2;n2.set[i] <- N2 + dN2;f2.set[i] <- F2 + dF2;e.set[i] <- E - (dN1 + dN2)
  
c1f1.set[i]<- c1tof1.new;c1f2.set[i]<- c1tof2.new;c2f1.set[i]<- c2tof1.new;c2f2.set[i]<- c2tof2.new
f1n1.set[i]<- f1ton1.new;f1n2.set[i]<- f1ton2.new;f2n1.set[i]<- f2ton1.new;f2n2.set[i]<- f2ton2.new
}

b1.resistance[j] = min(b1.set[round(0.55*length(tset),0):length(b1.set)])/b1.set[round(0.55*length(tset),0)]
b1.recovery_time[j] = max(tset)*(which(b1.set[round(0.6*length(tset),0):length(b1.set)] > 0.99*b1.set[round(0.55*length(tset),0)-1])[1] )/length(tset)
b1.recovery_percent[j] = b1.set[length(b1.set)]/b1.set[round(0.55*length(tset),0)-1]
f1.resistance[j] = min(f1.set[round(0.55*length(tset),0):length(f1.set)])/f1.set[round(0.55*length(tset),0)]
f1.recovery_time[j] = max(tset)*(which(f1.set[round(0.6*length(tset),0):length(f1.set)] > 0.99*f1.set[round(0.55*length(tset),0)-1])[1] )/length(tset)
f1.recovery_percent[j] = f1.set[length(f1.set)]/f1.set[round(0.55*length(tset),0)-1]
}
fungal_stress_response = samsetlong  %>% 
  rename(partner.preference = partner.pref) %>% 
  rename(ROI.host = roi.host) %>% 
  mutate(ROI.host = 1-ROI.host) %>% 
  rename(ROI.symb = roi.symb) %>% 
  mutate(ROI.symb = 1-ROI.symb)%>% 
  mutate(host_resistance = b1.resistance)%>% 
  mutate(host_recovery_time = b1.recovery_time)%>% 
  mutate(host_recovery_percent = b1.recovery_percent) %>% 
  mutate(host_resilience = host_recovery_percent/host_recovery_time) %>% 
  mutate(symb_resistance = f1.resistance)%>% 
  mutate(symb_recovery_time = f1.recovery_time)%>% 
  mutate(symb_recovery_percent = f1.recovery_percent) %>% 
  mutate(symb_resilience = symb_recovery_percent/symb_recovery_time) %>% 
  mutate(Fungal.ROI = ROI.symb)%>% 
  mutate(Host.ROI = ROI.host)

fungal_stress_scaled = fungal_stress_response %>% 
  mutate(partner.preference = 2*(partner.preference-0.5)) 
```

```{r}

df.set = fungal_stress_scaled %>% 
         filter(ROI.symb == 0)


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()
ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = fungal_stress_scaled %>% 
         filter(ROI.symb == unique(fungal_stress_scaled$ROI.symb)[5])


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = fungal_stress_scaled %>% 
         filter(ROI.symb == 1)


ggplot(df.set, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56")+
  labs(x = "Partner Preference", y = "Host ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.host), z = matrix(df.set$host_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Host ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")
```

```{r}

df.set = fungal_stress_scaled %>% 
         filter(ROI.host == 0)

ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = fungal_stress_scaled %>% 
         filter(ROI.host == unique(fungal_stress_scaled$ROI.symb)[5])


ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()
ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")


df.set = fungal_stress_scaled %>% 
         filter(ROI.host == 1)


ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resistance))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resistance")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()
ggplot(df.set, aes(x = partner.preference, y = ROI.symb, fill = symb_resilience))+ geom_tile()+
  scale_fill_gradient(low = "white", high = "#4e7a56", name = "Resilience")+
  labs(x = "Partner Preference", y = "Fungal ROI")+
  theme_minimal()

plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resilience, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
   xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = "")))


plot_ly(x = unique(df.set$partner.preference), y = unique(df.set$ROI.symb), z = matrix(df.set$symb_resistance, nrow = steps, ncol = steps, byrow = TRUE)) %>% add_surface()%>% layout(scene = list(
  xaxis=list(title = "Partner Preference"),yaxis=list(title = "Fungal ROI"),zaxis=list(title = ""))) %>% colorbar(title = "Resistance")
```


```{r}
opt_host = stress_scaled  %>% 
  group_by(ROI.host) %>%
  summarize(
    host_resistance = max(host_resistance)
  ) %>% 
  left_join(stress_scaled)

opt_symb = fungal_stress_scaled  %>% 
  group_by(ROI.host) %>%
  summarize(
    host_resistance = max(host_resistance)
  ) %>% 
  left_join(fungal_stress_scaled)


```



```{r, eval = F}
# host_resistance.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = host_resistance))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resistance")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Host Resistance (Minimum relative size of stressed host)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# host_recoverypercent.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = host_recovery_percent))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Recovery percent")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Host Percent host recovery after stress", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# host_recoverytime.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = host_recovery_time))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Time")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = " Host Time to full recovery", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# host_resilience.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = host_resilience))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resilience")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Host Resilience (% recovery/time to recovery)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# host_resistance.fung / host_recoverypercent.fung / host_recoverytime.fung / host_resilience.fung
# ggsave(here("src/piecemeal", "host_fungstress_superplot.png"), width = 14, height = 10)
# 
# #----------------------------------
# symb_resistance.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_resistance))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resistance")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Fungal Resistance (Minimum relative size of stressed host)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# symb_recoverypercent.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_recovery_percent))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Recovery percent")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Fungal Percent host recovery after stress", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# symb_recoverytime.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_recovery_time))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Time")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Fungal Time to full recovery", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# symb_resilience.fung = ggplot(fungal_stress_response, aes(x = partner.preference, y = ROI.host, fill = symb_resilience))+ geom_tile()+ 
#   scale_fill_viridis(discrete=FALSE, option="plasma", name = "Resilience")+facet_grid(cols = vars(Fungal.ROI), labeller = label_both)+ theme(aspect.ratio=15/15)+ 
#   labs(title = "Fungal Resilience (% recovery/time to recovery)", x = "Percent Allocation to Preferred Partner", y = "Host % ROI")
# 
# symb_resistance.fung / symb_recoverypercent.fung / symb_recoverytime.fung / symb_resilience.fung
# ggsave(here("src/piecemeal", "symb_fungstress_superplot.png"), width = 14, height = 10)

```

